name: Notify Slack on merged pull requests

on:
  pull_request:
    types:
      - closed
    branches:    
      - master
      - test

jobs:
  notify_merged_pull_request:
    name: Notify Slack on merged pull requests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          channel-id: 'C01KYA95GFK'
          payload: |
            {
                "text": "${{ github.event.pull_request }}"
            }
        uses: slackapi/slack-github-action@v1.25.0
